set_property PACKAGE_PIN V19 [get_ports {q_out[3]}]
set_property PACKAGE_PIN U19 [get_ports {q_out[2]}]
set_property PACKAGE_PIN E19 [get_ports {q_out[1]}]
set_property PACKAGE_PIN U16 [get_ports {q_out[0]}]
set_property PACKAGE_PIN A16 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {q_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
